spring:
  application:
    name: disruptor
#  #数据源基本配置
#  datasource:
#    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: ${db.user}
#    password: ${db.pass}
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 数据源其它配置
#    druid:
#      # 连接池的配置信息
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      use-global-data-source-stat: true
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#  # redis 配置
#  redis:
#    # Redis数据库索引（默认为0）
#    database: ${redis.database}
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: ${redis.port}
#    # Redis服务器连接密码（默认为空）
#    password: ${redis.password}
#    # 连接池最大连接数（使用负值表示没有限制）
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 20
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 10000ms
#        # 连接池中的最大空闲连接
#        max-idle: 5
#        # 连接池中的最小空闲连接
#        min-idle: 2
#    lettuce:
#      pool:
#        max-active: 20
#        max-idle: 5
#        max-wait: 10000ms
#        min-idle: 2
#      shutdown-timeout: 3000ms
#  # jpa设置
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database: mysql
  # springboot 环境设置
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false

# 服务配置
server:
  port: ${tomcat.port}
  tomcat:
    uri-encoding: UTF-8


# 日志设置
logging:
  config: classpath:conf/logback-spring.xml
